[package]
name = "primit"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rand = "*"
sha2 = "*"
md-5 = "*"
chacha20 = "*"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "fat"
opt-level = "s"
panic = "abort"
