[package]
name = "primit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
# hex-simd = "0.5.0"
# hex = "*"
sha2 = "*"
ring = "*"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "fat"
opt-level = 'z'
panic = "abort"
